name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: mvn test

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

      - name: Build Docker image
        run: |
          docker build -t gamifiedbudgetapp .
          docker tag gamifiedbudgetapp:latest 739561935927.dkr.ecr.us-east-2.amazonaws.com/gamifiedbudgetapp:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 739561935927.dkr.ecr.us-east-2.amazonaws.com/gamifiedbudgetapp:latest

      - name: Update Kubernetes deployment
        run: |
          aws eks update-kubeconfig --region us-east-2 --name budget-game
          kubectl set image deployment/gamifiedbudgetapp-deployment gamifiedbudgetapp-container=739561935927.dkr.ecr.us-east-2.amazonaws.com/gamifiedbudgetapp:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2